name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'extension version'
        required: false
        type: string

jobs:
  build:
    name: Create release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update tags
        id: update_tags
        uses: dae-ne/update-tags@main
        with:
          version: ${{ github.event.inputs.version }}
      # - name: Create Release
      #   uses: dae-ne/create-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag-name: ${{ steps.update_tags.outputs.version }}
      #     name: Release ${{ steps.update_tags.outputs.version }}
